### ISSUE TITLE
Factor out the "quizz" feature as a standalone app?

### ISSUE THREAD

**Issue by bzg** [DISIC/MiNumEco#80]
AFAIU, the quizz feature is integrated into this repository.

Is it usable outside "greentech"?  If not (yet), can it be factored out? And/or available as a [dsfr](https://github.com/GouvernementFR/dsfr) component?

There are potentially a lot of reusers!

**Comment by bzg** [comment]
A discrete ping just to know if someone is overseeing this.

**Comment by bzg** [comment]
Just another ping in case someone is listening :)

**Comment by supertanuki** [comment]
@bzg hello Bastien, sorry, I have to find the time to do it!

**Comment by bzg** [comment]
No problem! In your own time, of course. This was just an idea.

**Comment by bzg** [comment]
I assume this repository is not maintained anymore, so I'm closing this now.
